#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MINIMUM_MOTORINO_INTENSITY 200
#define MOTORINO_PIN 12
#define MOTORINO_LEDC_CHANNEL 0
#define MOTORINO_LEDC_RESOLUTION 8
#define MOTORINO_LEDC_FREQUENCY 4000
#define MOTORINO_TASK_PRIORITY 1
#define MOTORINO_TASK_CORE 0
#define MOTORINO_TEMPO_FRA_VIBRAZIONI 200
#define ENCODER_CLK_PIN 26
#define ENCODER_DT_PIN 25
#define ENCODER_PPR 40
#define SCHERMO_PIN_SDA 21
#define SCHERMO_PIN_SCL 22

#define API_URL "http://192.168.197.52/"
#define SCHERMO_PIN_1 21
#define SCHERMO_PIN_2 22
#define TIMEOUT_NEW_CREDENTIALS_MILLISECONDS 20000

#define TIMEOUT_STOP_TRAINING_MILLISECONDS 3000
#define SAMPLE_SENDING_PERIOD_SECONDS 10

#define CONFIGURATION_SSID "JMPCorda"
#define LENGTH 8
#define CHARS "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

// Wifi constants

#endif