#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MINIMUM_MOTORINO_INTENSITY 200
#define MOTORINO_PIN 12
#define MOTORINO_LEDC_CHANNEL 0
#define MOTORINO_LEDC_RESOLUTION 8
#define MOTORINO_LEDC_FREQUENCY 4000
#define MOTORINO_TASK_PRIORITY 1
#define MOTORINO_TASK_CORE 0
#define MOTORINO_TEMPO_FRA_VIBRAZIONI 200
#define ENCODER_CLK_PIN 26
#define ENCODER_DT_PIN 25
#define ENCODER_PPR 40
#define SCHERMO_PIN_SDA 21
#define SCHERMO_PIN_SCL 22

#define API_URL "http://el.mogus"

#define TIMEOUT_STOP_TRAINING_MILLISECONDS 3000
#define SAMPLE_SENDING_PERIOD_SECONDS 2

// Wifi constants

#endif