#ifndef CONSTANTS_H
#define CONSTANTS_H

#define ENCODER_CLK_PIN 26
#define ENCODER_DT_PIN 25
#define ENCODER_PPR 40

// Wifi constants

#define DEFAULT_TEMPORARY_NETWORK_SSID "ConfigurazioneCorda"
#define DEFAULT_TEMPORARY_NETWORK_PASSWORD "elSugusWifi"
#define DEFAULT_MICROCONTROLLER_IP 192, 168, 4, 1
#define DEFAULT_TEMPORARY_NETWORK_GATEWAY 192, 168, 4, 1
#define DEFAULT_TEMPORARY_NETWORK_SUBNET_MASK 255 , 255, 255, 0

#endif