version: "3.9"
services:
  php-apache:
    image: php:8.2.4-apache
    ports:
      - "80:80"
    build: './build/php'
    #restart: always
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    build: './build/mysql'
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "super-secret-password"
      MYSQL_DATABASE: "my-wonderful-website"
      #MYSQL_USER: "utente"
      #MYSQL_PASSWORD: "passwordUtente"
    volumes:
      - dbData:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    build: './build/phpmyadmin'
    ports:
      - "8080:80"
    #restart: always
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
volumes:
  app:
  dbData:
